service: practical-4-rag-vector
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    REDIS_URL: ${env:REDIS_URL}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

plugins:
  - serverless-offline

functions:
  ask:
    handler: handler.ask
    events:
      - http:
          path: ask
          method: post
          cors: true
